spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: hrms
    password: hrms123
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8080

app:
  jwt:
    issuer: employee-portal
    secret: ${JWT_SECRET:change-me-please-32+chars}
    access-token-ttl-min: 60
